import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { FileText, LoaderCircle, Plus, X } from 'lucide-react';
import { supabase, useAuth } from '@/lib/auth';

type Application={id:string;organization_id:string|null;user_id:string;type:string;title:string;description:string|null;start_date:string;end_date:string;status:string;admin_note:string|null;created_at:string};
const types=['leave','remote','half_day','other'];
export function ApplicationsView(){const{profile}=useAuth();const[items,setItems]=useState<Application[]>([]);const[loading,setLoading]=useState(true);const[open,setOpen]=useState(false);const[saving,setSaving]=useState(false);
const load=useCallback(async()=>{if(!supabase||!profile?.id){setLoading(false);return;}const q=supabase.from('applications').select('*').order('created_at',{ascending:false}); const{data}=profile.role==='admin'||profile.role==='super_admin'?await q:await q.eq('user_id',profile.id);setItems((data as Application[])||[]);setLoading(false)},[profile?.id]);useEffect(()=>{void load()},[load]);
const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!supabase||!profile?.id)return;setSaving(true);const f=new FormData(e.currentTarget);const{error}=await supabase.from('applications').insert({user_id:profile.id,type:String(f.get('type')),title:String(f.get('title')),description:String(f.get('description')||'')||null,start_date:String(f.get('start_date')),end_date:String(f.get('end_date')),status:'pending',organization_id:profile.organization?.id || null});setSaving(false);if(!error){setOpen(false);void load()}};return <div className="merged-oms section-view"><div className="page-heading"><div><div className="eyebrow dark"><span className="eyebrow-dot"/> Requests & approvals</div><h1>Applications</h1><p>Submit and track leave, remote-work and other office requests.</p></div><button className="primary-button" onClick={()=>setOpen(true)}><Plus size={16}/> New application</button></div>
{loading?<div className="panel empty-state"><LoaderCircle className="spin"/> Loading applications...</div>:items.length===0?<div className="panel empty-state"><FileText size={28}/><strong>No applications yet</strong><span>Your submitted requests will appear here.</span></div>:<div className="table-wrap"><table><thead><tr><th>Request</th><th>Type</th><th>Dates</th><th>Status</th></tr></thead><tbody>{items.map(a=><tr key={a.id}><td><strong>{a.title}</strong><small>{a.description||'—'}</small></td><td>{a.type.replace('_',' ')}</td><td>{a.start_date} → {a.end_date}</td><td><span className={`status-badge ${a.status}`}>{a.status}</span>
{(profile.role==='admin'||profile.role==='super_admin')&&a.status==='pending'&&<div className="inline-actions"><button type="button" onClick={async()=>{if(!supabase)return;await supabase.from('applications').update({status:'approved',reviewed_at:new Date().toISOString()}).eq('id',a.id);void load()}}>Approve</button><button type="button" onClick={async()=>{if(!supabase)return;await supabase.from('applications').update({status:'rejected',reviewed_at:new Date().toISOString()}).eq('id',a.id);void load()}}>Reject</button></div>}</td></tr>)}</tbody></table></div>}
{open&&<div className="modal-backdrop" onMouseDown={()=>setOpen(false)}><div className="modal-card" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><h2>New application</h2><button onClick={()=>setOpen(false)}><X size={18}/></button></div><form onSubmit={submit} className="form-stack"><label className="form-field"><span>Type</span><select name="type">{types.map(t=><option key={t}>{t}</option>)}</select></label><label className="form-field"><span>Title</span><input name="title" required placeholder="Annual leave request"/></label><label className="form-field"><span>Start date</span><input name="start_date" type="date" required/></label><label className="form-field"><span>End date</span><input name="end_date" type="date" required/></label><label className="form-field"><span>Description</span><textarea name="description" rows={4}/></label><button className="primary-button" disabled={saving}>{saving?<LoaderCircle className="spin" size={16}/>:<Plus size={16}/>} Submit application</button></form></div></div>}</div>}
